<div data-github-url="https://github.com/kamranahmedse/developer-roadmap/tree/master/src/data/roadmaps/nodejs/content/103-nodejs-error-handling/104-async-errors.md"></div> <h1 id="async-errors">Async errors</h1>
<p>Errors must always be handled. If you are using synchronous programming you could use a try catch. But this does not work if you work asynchronous! Async errors will only be handled inside the callback function!</p>
<p>Visit the following resources to learn more:</p>
<ul>
<li><a href="https://www.mariokandut.com/handling-errors-in-asynchronous-functions-node-js/" rel="noopener noreferrer nofollow" target="_blank">@article@Async Errors</a></li>
</ul>